server:
  port: 11001
spring:
  kafka:
    bootstrap-servers: http://118.24.232.124:9092,http://118.24.232.124:9093,http://118.24.232.124:9094
    consumer:
      group-id: mygroup
      auto-offset-reset: latest
      enable-auto-commit: true
logging:
  config: log4j2.xml